name: Save Artifacts After Merge

# プルリクエストがマージされた後、特定のブランチにpushされたときに実行
on:
  push:
    branches:
      - main  # マージ先のブランチを指定

jobs:
  save-artifacts:
    runs-on: ubuntu-latest

    steps:
    # リポジトリをクローン
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 21.5.0
        registry-url: https://npm.pkg.github.com/

    - name: Setup PNPM
      uses: pnpm/action-setup@v2.4.1
      with:
        version: 8.14.1

    # スナップショットを保存
    - name: Run save-snapshot
      run: pnpm save-snapshot

    # アーティファクトをアップロード
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: expected-reg  # アーティファクトの名前
        path: .reg/expected  # 保存するディレクトリ
